Add controllers
lazarx77/java-shareit pull request #1
Opened 2024-09-04 19:27 UTC by lazarx77

Доработка функционала согласно ТЗ спринта 14.

2024-09-05 17:51 UTC, kriwsha requested changes

2024-09-05 17:51 UTC, kriwsha commented on README.md
> +Доработка функционала согласно ТЗ спринта 14.
Вообще, функционал != функциональность. Функционал, простыми словами, - это функция от функции. А реализуем мы функциональности. Но да, "функционал" вы будете слышать чаще, хотя это неправильно))

2024-09-05 17:51 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/exception/ItemDoNotBelongToUser.java
> + * Исключение ItemDoNotBelongToUser представляет собой пользовательское исключение,
Суперподробное описание - это и хорошо, и плохо. С одной стороны, вы хорошо и понятно объяснили. С другой стороны, вряд ли кто это дочитает до конца. Оставляю на ваш выбор, но на реальных проектах лучше писать кратко (я бы сказал, лапидарно=) ). Н-р, "Исключение для случая, когда предметом пытается управлять тот, кому предмет не принадлежит". То, что это RuntimeException, видно из сигнатуры класса (об этом можно в комментарии не писать).

2024-09-05 17:51 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/InMemoryItemRepository.java
> + * Класс InMemoryItemRepository реализует интерфейс ItemRepository и предоставляет
Здесь тоже можно сократить. В комментарии лучше писать назначение без технической реализации: то, что класс реализует интерфейс, видно из сигнатуры класса.

2024-09-05 17:51 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> + *         {@link #addNewItem(Long, ItemDto)} - добавляет новый предмет в систему.
Описание методов лучше оставить нам самими методами

2024-09-05 17:51 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/ItemValidatorService.java
> +@Service
У вас классе один статический метод. Класс больше похож на утилитарный класс. Доступаетесь вы до него не через создание бина, а через имя класса. Поэтому аннотация Service здесь не нужна.

2024-09-05 17:51 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/user/UserValidatorService.java
> +            if (user1.equals(user)) { //@EqualsAndHashCode(of = "email")
Закомментированный код лучше удалять. И еще я бы все таки явно сравнивал емайлы. Без комментария логика неочевидна, что может вызвать путаницу.

2024-09-05 17:51 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/user/UserValidatorService.java
> +        for (User user1 : users) {
Я стараюсь не называть переменные с цифрами, если этого не требуется явно. Н-р, если нужно создать переменную, которая хранит строку "ГОСТ Р ИСО/МЭК 20546-2021", то да, тут ее можно назвать GOST_20546_2021. Но когда у нас две переменные с одинаковыми названиями, то я называю либо "sourceUser <-> targetUser", либо "sourceUser <-> currentUser". Но это только рекомендация.

2024-09-06 06:05 UTC, lazarx77 commented on README.md
> +Доработка функционала согласно ТЗ спринта 14.
Меня и самого с самого начала размещения пулл-реквестов на гитхабе это коробило, но я делал, как было написано в примере. Поправил :-)

2024-09-06 06:06 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/exception/ItemDoNotBelongToUser.java
> + * Исключение ItemDoNotBelongToUser представляет собой пользовательское исключение,
На самом деле я не знаю, когда вовремя остановиться :-). Учитывая, что я осознаю, что это учебный проект, я пробую разные варианты комментариев, чтобы посмотреть, как это все работает. Я пробежался по всему проекту и убрал избыточную (на мой взгляд) информацию из комментариев.

2024-09-06 06:06 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/item/InMemoryItemRepository.java
> + * Класс InMemoryItemRepository реализует интерфейс ItemRepository и предоставляет
Хорошо. Пока немного не понимаю, когда вовремя остановиться. Спасибо за разъяснения :-).

2024-09-06 06:06 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> + *         {@link #addNewItem(Long, ItemDto)} - добавляет новый предмет в систему.
Поправил комментарии по всему проекту - убрал избыточное описание методов из "шапки" классов :-).

2024-09-06 06:06 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/item/ItemValidatorService.java
> +@Service
Действительно, я об этом не подумал. Видимо, аннотацию Service поставил на автомате, так как класс называется тоже "...service". Поправил :-)

2024-09-06 06:07 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/user/UserValidatorService.java
> +            if (user1.equals(user)) { //@EqualsAndHashCode(of = "email")
Изначально сделал так, так как было интересно посмотреть, а "сработает ли" такая реализация. Комментарий убрал, прописал явную проверку email пользователей, внес изменения в методы обновления пользователей в UserServiceImpl и InMemoryUserRepository.  Также убрал ненужную аннотацию Service у класса.

2024-09-06 06:08 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/user/UserValidatorService.java
> +        for (User user1 : users) {
Согласен, мне sourceUser и currentUser тоже нравятся больше. Поправил.

Как всегда, большое спасибо за полезные рекомендации!👍🤝

2024-09-07 05:03 UTC, kriwsha approved these changes

2024-09-10 15:41 UTC, merged