Add bookings
lazarx77/java-shareit pull request #2
Opened 2024-09-21 11:13 UTC by lazarx77

Добавлены работа с базой данных, бронирование предметов, а также возможность добавления отзывов - согласно ТЗ спринта 15.
Выполнил Олег Лазаренко.

2024-09-21 18:40 UTC, kriwsha requested changes

2024-09-21 18:40 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                .findAllBookingsOfBooker(userId, state).stream().map(BookingMapper::mapToBookingDto).toList();
Стримы лучше разбивать на несколько строк для лучшей читаемости. Если код "убегает за экран", то понимать его сложно. Я бы рекомендовал разбить по точкам.

2024-09-21 18:40 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    LinkedList<Booking> findAllBookingsByBooker_idOrderByStartDesc(Long bookerId);
Не забывайте про полиморфизм. Вам необходимо использовать интерфейсы. Даже если вам необходимо внутри создать LinkedList, вам возвращать нужно интерфейс. Ничего от этого не изменится - данные все равно будут храниться в LinkedList'е, даже если возвращаемым значением будет List. Следует везде поправить

2024-09-21 18:40 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    BookingRepository bookingRepository;
Не забывайте про инкапсуляцию - используйте модификаторы

2024-09-21 18:40 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/BookingValidatorService.java
> +public class BookingValidatorService {
Я бы не стал добавлять Service - может создаться впечатление, что это спринговый сервис. Однако это просто утилка, поэтому либо заканчиваться на Utils (и тогда будет что-то вроде BookingValidationUtils), либо просто BookingValidator.

2024-09-21 18:40 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/dto/BookingAddDto.java
> +    Long id;
Модификаторы доступа

2024-09-21 18:40 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    Long id;
Модификаторы доступа

2024-09-21 18:40 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    Long id;
Модификаторы доступа

2024-09-21 18:40 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    Long id;
модификаторы доступа

2024-09-22 06:05 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                .findAllBookingsOfBooker(userId, state).stream().map(BookingMapper::mapToBookingDto).toList();
Пробежался по всему коду. Поправил.

2024-09-22 06:05 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    LinkedList<Booking> findAllBookingsByBooker_idOrderByStartDesc(Long bookerId);
Исправил.

2024-09-22 06:06 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    BookingRepository bookingRepository;
Моя невнимательность. Исправил.

2024-09-22 06:11 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/booking/BookingValidatorService.java
> +public class BookingValidatorService {
Переименовал все свои валидаторы.

2024-09-22 06:11 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingAddDto.java
> +    Long id;
Думаю, мне уже пора сделать памятку (чеклист) перед отправкой проекта на проверку - проверять модификаторы доступа))). Исправил.

2024-09-22 06:11 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    Long id;
Исправил.

2024-09-22 06:11 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    Long id;
Исправил.

2024-09-22 06:11 UTC, lazarx77 commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    Long id;
Исправил.

2024-09-23 06:23 UTC, kriwsha approved these changes

2024-09-23 06:27 UTC, merged